// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/Yusufdot101/ripple/services/user/internal/application/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockAuthService {
	mock := &MockAuthService{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// ActivateAccount provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ActivateAccount(tokenString string, identityID uint) (string, string, error) {
	ret := _mock.Called(tokenString, identityID)

	if len(ret) == 0 {
		panic("no return value specified for ActivateAccount")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, uint) (string, string, error)); ok {
		return returnFunc(tokenString, identityID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint) string); ok {
		r0 = returnFunc(tokenString, identityID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint) string); ok {
		r1 = returnFunc(tokenString, identityID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, uint) error); ok {
		r2 = returnFunc(tokenString, identityID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_ActivateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateAccount'
type MockAuthService_ActivateAccount_Call struct {
	*mock.Call
}

// ActivateAccount is a helper method to define mock.On call
//   - tokenString string
//   - identityID uint
func (_e *MockAuthService_Expecter) ActivateAccount(tokenString interface{}, identityID interface{}) *MockAuthService_ActivateAccount_Call {
	return &MockAuthService_ActivateAccount_Call{Call: _e.mock.On("ActivateAccount", tokenString, identityID)}
}

func (_c *MockAuthService_ActivateAccount_Call) Run(run func(tokenString string, identityID uint)) *MockAuthService_ActivateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_ActivateAccount_Call) Return(s string, s1 string, err error) *MockAuthService_ActivateAccount_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *MockAuthService_ActivateAccount_Call) RunAndReturn(run func(tokenString string, identityID uint) (string, string, error)) *MockAuthService_ActivateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// BeginAuth provides a mock function for the type MockAuthService
func (_mock *MockAuthService) BeginAuth(providerName string) (string, string, string, error) {
	ret := _mock.Called(providerName)

	if len(ret) == 0 {
		panic("no return value specified for BeginAuth")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, string, string, error)); ok {
		return returnFunc(providerName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(providerName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) string); ok {
		r1 = returnFunc(providerName)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string) string); ok {
		r2 = returnFunc(providerName)
	} else {
		r2 = ret.Get(2).(string)
	}
	if returnFunc, ok := ret.Get(3).(func(string) error); ok {
		r3 = returnFunc(providerName)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockAuthService_BeginAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginAuth'
type MockAuthService_BeginAuth_Call struct {
	*mock.Call
}

// BeginAuth is a helper method to define mock.On call
//   - providerName string
func (_e *MockAuthService_Expecter) BeginAuth(providerName interface{}) *MockAuthService_BeginAuth_Call {
	return &MockAuthService_BeginAuth_Call{Call: _e.mock.On("BeginAuth", providerName)}
}

func (_c *MockAuthService_BeginAuth_Call) Run(run func(providerName string)) *MockAuthService_BeginAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_BeginAuth_Call) Return(authURL string, state string, nonce string, err error) *MockAuthService_BeginAuth_Call {
	_c.Call.Return(authURL, state, nonce, err)
	return _c
}

func (_c *MockAuthService_BeginAuth_Call) RunAndReturn(run func(providerName string) (string, string, string, error)) *MockAuthService_BeginAuth_Call {
	_c.Call.Return(run)
	return _c
}

// HandleAuth provides a mock function for the type MockAuthService
func (_mock *MockAuthService) HandleAuth(ctx context.Context, credentials map[string]string, provider string) (string, string, error) {
	ret := _mock.Called(ctx, credentials, provider)

	if len(ret) == 0 {
		panic("no return value specified for HandleAuth")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, string) (string, string, error)); ok {
		return returnFunc(ctx, credentials, provider)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, string) string); ok {
		r0 = returnFunc(ctx, credentials, provider)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string, string) string); ok {
		r1 = returnFunc(ctx, credentials, provider)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, map[string]string, string) error); ok {
		r2 = returnFunc(ctx, credentials, provider)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_HandleAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAuth'
type MockAuthService_HandleAuth_Call struct {
	*mock.Call
}

// HandleAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - credentials map[string]string
//   - provider string
func (_e *MockAuthService_Expecter) HandleAuth(ctx interface{}, credentials interface{}, provider interface{}) *MockAuthService_HandleAuth_Call {
	return &MockAuthService_HandleAuth_Call{Call: _e.mock.On("HandleAuth", ctx, credentials, provider)}
}

func (_c *MockAuthService_HandleAuth_Call) Run(run func(ctx context.Context, credentials map[string]string, provider string)) *MockAuthService_HandleAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthService_HandleAuth_Call) Return(refreshToken string, accessToken string, err error) *MockAuthService_HandleAuth_Call {
	_c.Call.Return(refreshToken, accessToken, err)
	return _c
}

func (_c *MockAuthService_HandleAuth_Call) RunAndReturn(run func(ctx context.Context, credentials map[string]string, provider string) (string, string, error)) *MockAuthService_HandleAuth_Call {
	_c.Call.Return(run)
	return _c
}

// NewUser provides a mock function for the type MockAuthService
func (_mock *MockAuthService) NewUser(user *domain.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for NewUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_NewUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewUser'
type MockAuthService_NewUser_Call struct {
	*mock.Call
}

// NewUser is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockAuthService_Expecter) NewUser(user interface{}) *MockAuthService_NewUser_Call {
	return &MockAuthService_NewUser_Call{Call: _e.mock.On("NewUser", user)}
}

func (_c *MockAuthService_NewUser_Call) Run(run func(user *domain.User)) *MockAuthService_NewUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_NewUser_Call) Return(err error) *MockAuthService_NewUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_NewUser_Call) RunAndReturn(run func(user *domain.User) error) *MockAuthService_NewUser_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyUsers provides a mock function for the type MockAuthService
func (_mock *MockAuthService) VerifyUsers(ctx context.Context, userIDs []uint32) (bool, error) {
	ret := _mock.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for VerifyUsers")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint32) (bool, error)); ok {
		return returnFunc(ctx, userIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint32) bool); ok {
		r0 = returnFunc(ctx, userIDs)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint32) error); ok {
		r1 = returnFunc(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_VerifyUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyUsers'
type MockAuthService_VerifyUsers_Call struct {
	*mock.Call
}

// VerifyUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []uint32
func (_e *MockAuthService_Expecter) VerifyUsers(ctx interface{}, userIDs interface{}) *MockAuthService_VerifyUsers_Call {
	return &MockAuthService_VerifyUsers_Call{Call: _e.mock.On("VerifyUsers", ctx, userIDs)}
}

func (_c *MockAuthService_VerifyUsers_Call) Run(run func(ctx context.Context, userIDs []uint32)) *MockAuthService_VerifyUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint32
		if args[1] != nil {
			arg1 = args[1].([]uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_VerifyUsers_Call) Return(b bool, err error) *MockAuthService_VerifyUsers_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAuthService_VerifyUsers_Call) RunAndReturn(run func(ctx context.Context, userIDs []uint32) (bool, error)) *MockAuthService_VerifyUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockMailer {
	mock := &MockMailer{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockMailer
func (_mock *MockMailer) Send(recipient string, templateFile string, data any) error {
	ret := _mock.Called(recipient, templateFile, data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, any) error); ok {
		r0 = returnFunc(recipient, templateFile, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMailer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - recipient string
//   - templateFile string
//   - data any
func (_e *MockMailer_Expecter) Send(recipient interface{}, templateFile interface{}, data interface{}) *MockMailer_Send_Call {
	return &MockMailer_Send_Call{Call: _e.mock.On("Send", recipient, templateFile, data)}
}

func (_c *MockMailer_Send_Call) Run(run func(recipient string, templateFile string, data any)) *MockMailer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMailer_Send_Call) Return(err error) *MockMailer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailer_Send_Call) RunAndReturn(run func(recipient string, templateFile string, data any) error) *MockMailer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthProviderRegistry creates a new instance of MockAuthProviderRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthProviderRegistry(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockAuthProviderRegistry {
	mock := &MockAuthProviderRegistry{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthProviderRegistry is an autogenerated mock type for the AuthProviderRegistry type
type MockAuthProviderRegistry struct {
	mock.Mock
}

type MockAuthProviderRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthProviderRegistry) EXPECT() *MockAuthProviderRegistry_Expecter {
	return &MockAuthProviderRegistry_Expecter{mock: &_m.Mock}
}

// GetOauthProvider provides a mock function for the type MockAuthProviderRegistry
func (_mock *MockAuthProviderRegistry) GetOauthProvider(provider string) (OAuthProvider, error) {
	ret := _mock.Called(provider)

	if len(ret) == 0 {
		panic("no return value specified for GetOauthProvider")
	}

	var r0 OAuthProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (OAuthProvider, error)); ok {
		return returnFunc(provider)
	}
	if returnFunc, ok := ret.Get(0).(func(string) OAuthProvider); ok {
		r0 = returnFunc(provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(OAuthProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(provider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProviderRegistry_GetOauthProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOauthProvider'
type MockAuthProviderRegistry_GetOauthProvider_Call struct {
	*mock.Call
}

// GetOauthProvider is a helper method to define mock.On call
//   - provider string
func (_e *MockAuthProviderRegistry_Expecter) GetOauthProvider(provider interface{}) *MockAuthProviderRegistry_GetOauthProvider_Call {
	return &MockAuthProviderRegistry_GetOauthProvider_Call{Call: _e.mock.On("GetOauthProvider", provider)}
}

func (_c *MockAuthProviderRegistry_GetOauthProvider_Call) Run(run func(provider string)) *MockAuthProviderRegistry_GetOauthProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthProviderRegistry_GetOauthProvider_Call) Return(oAuthProvider OAuthProvider, err error) *MockAuthProviderRegistry_GetOauthProvider_Call {
	_c.Call.Return(oAuthProvider, err)
	return _c
}

func (_c *MockAuthProviderRegistry_GetOauthProvider_Call) RunAndReturn(run func(provider string) (OAuthProvider, error)) *MockAuthProviderRegistry_GetOauthProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetProvider provides a mock function for the type MockAuthProviderRegistry
func (_mock *MockAuthProviderRegistry) GetProvider(provider string) (Provider, error) {
	ret := _mock.Called(provider)

	if len(ret) == 0 {
		panic("no return value specified for GetProvider")
	}

	var r0 Provider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Provider, error)); ok {
		return returnFunc(provider)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Provider); ok {
		r0 = returnFunc(provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Provider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(provider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProviderRegistry_GetProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProvider'
type MockAuthProviderRegistry_GetProvider_Call struct {
	*mock.Call
}

// GetProvider is a helper method to define mock.On call
//   - provider string
func (_e *MockAuthProviderRegistry_Expecter) GetProvider(provider interface{}) *MockAuthProviderRegistry_GetProvider_Call {
	return &MockAuthProviderRegistry_GetProvider_Call{Call: _e.mock.On("GetProvider", provider)}
}

func (_c *MockAuthProviderRegistry_GetProvider_Call) Run(run func(provider string)) *MockAuthProviderRegistry_GetProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthProviderRegistry_GetProvider_Call) Return(provider1 Provider, err error) *MockAuthProviderRegistry_GetProvider_Call {
	_c.Call.Return(provider1, err)
	return _c
}

func (_c *MockAuthProviderRegistry_GetProvider_Call) RunAndReturn(run func(provider string) (Provider, error)) *MockAuthProviderRegistry_GetProvider_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockProvider {
	mock := &MockProvider{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockProvider
func (_mock *MockProvider) Authenticate(ctx context.Context, inputs map[string]string) (*domain.UserIdentity, error) {
	ret := _mock.Called(ctx, inputs)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.UserIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) (*domain.UserIdentity, error)); ok {
		return returnFunc(ctx, inputs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) *domain.UserIdentity); ok {
		r0 = returnFunc(ctx, inputs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = returnFunc(ctx, inputs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockProvider_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - inputs map[string]string
func (_e *MockProvider_Expecter) Authenticate(ctx interface{}, inputs interface{}) *MockProvider_Authenticate_Call {
	return &MockProvider_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, inputs)}
}

func (_c *MockProvider_Authenticate_Call) Run(run func(ctx context.Context, inputs map[string]string)) *MockProvider_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Authenticate_Call) Return(userIdentity *domain.UserIdentity, err error) *MockProvider_Authenticate_Call {
	_c.Call.Return(userIdentity, err)
	return _c
}

func (_c *MockProvider_Authenticate_Call) RunAndReturn(run func(ctx context.Context, inputs map[string]string) (*domain.UserIdentity, error)) *MockProvider_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthProvider creates a new instance of MockOAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockOAuthProvider {
	mock := &MockOAuthProvider{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOAuthProvider is an autogenerated mock type for the OAuthProvider type
type MockOAuthProvider struct {
	mock.Mock
}

type MockOAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthProvider) EXPECT() *MockOAuthProvider_Expecter {
	return &MockOAuthProvider_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockOAuthProvider
func (_mock *MockOAuthProvider) Authenticate(ctx context.Context, inputs map[string]string) (*domain.UserIdentity, error) {
	ret := _mock.Called(ctx, inputs)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.UserIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) (*domain.UserIdentity, error)); ok {
		return returnFunc(ctx, inputs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string) *domain.UserIdentity); ok {
		r0 = returnFunc(ctx, inputs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = returnFunc(ctx, inputs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOAuthProvider_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockOAuthProvider_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - inputs map[string]string
func (_e *MockOAuthProvider_Expecter) Authenticate(ctx interface{}, inputs interface{}) *MockOAuthProvider_Authenticate_Call {
	return &MockOAuthProvider_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, inputs)}
}

func (_c *MockOAuthProvider_Authenticate_Call) Run(run func(ctx context.Context, inputs map[string]string)) *MockOAuthProvider_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOAuthProvider_Authenticate_Call) Return(userIdentity *domain.UserIdentity, err error) *MockOAuthProvider_Authenticate_Call {
	_c.Call.Return(userIdentity, err)
	return _c
}

func (_c *MockOAuthProvider_Authenticate_Call) RunAndReturn(run func(ctx context.Context, inputs map[string]string) (*domain.UserIdentity, error)) *MockOAuthProvider_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthURL provides a mock function for the type MockOAuthProvider
func (_mock *MockOAuthProvider) GetAuthURL(state string, nonce string) string {
	ret := _mock.Called(state, nonce)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(state, nonce)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOAuthProvider_GetAuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthURL'
type MockOAuthProvider_GetAuthURL_Call struct {
	*mock.Call
}

// GetAuthURL is a helper method to define mock.On call
//   - state string
//   - nonce string
func (_e *MockOAuthProvider_Expecter) GetAuthURL(state interface{}, nonce interface{}) *MockOAuthProvider_GetAuthURL_Call {
	return &MockOAuthProvider_GetAuthURL_Call{Call: _e.mock.On("GetAuthURL", state, nonce)}
}

func (_c *MockOAuthProvider_GetAuthURL_Call) Run(run func(state string, nonce string)) *MockOAuthProvider_GetAuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOAuthProvider_GetAuthURL_Call) Return(s string) *MockOAuthProvider_GetAuthURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOAuthProvider_GetAuthURL_Call) RunAndReturn(run func(state string, nonce string) string) *MockOAuthProvider_GetAuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIdentityRepository creates a new instance of MockIdentityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockIdentityRepository {
	mock := &MockIdentityRepository{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdentityRepository is an autogenerated mock type for the IdentityRepository type
type MockIdentityRepository struct {
	mock.Mock
}

type MockIdentityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityRepository) EXPECT() *MockIdentityRepository_Expecter {
	return &MockIdentityRepository_Expecter{mock: &_m.Mock}
}

// ActivateIdentity provides a mock function for the type MockIdentityRepository
func (_mock *MockIdentityRepository) ActivateIdentity(identityID uint) error {
	ret := _mock.Called(identityID)

	if len(ret) == 0 {
		panic("no return value specified for ActivateIdentity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(identityID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdentityRepository_ActivateIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateIdentity'
type MockIdentityRepository_ActivateIdentity_Call struct {
	*mock.Call
}

// ActivateIdentity is a helper method to define mock.On call
//   - identityID uint
func (_e *MockIdentityRepository_Expecter) ActivateIdentity(identityID interface{}) *MockIdentityRepository_ActivateIdentity_Call {
	return &MockIdentityRepository_ActivateIdentity_Call{Call: _e.mock.On("ActivateIdentity", identityID)}
}

func (_c *MockIdentityRepository_ActivateIdentity_Call) Run(run func(identityID uint)) *MockIdentityRepository_ActivateIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIdentityRepository_ActivateIdentity_Call) Return(err error) *MockIdentityRepository_ActivateIdentity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdentityRepository_ActivateIdentity_Call) RunAndReturn(run func(identityID uint) error) *MockIdentityRepository_ActivateIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUnverifiedIdentities provides a mock function for the type MockIdentityRepository
func (_mock *MockIdentityRepository) DeleteUnverifiedIdentities(provider string, sub string) error {
	ret := _mock.Called(provider, sub)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUnverifiedIdentities")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(provider, sub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdentityRepository_DeleteUnverifiedIdentities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUnverifiedIdentities'
type MockIdentityRepository_DeleteUnverifiedIdentities_Call struct {
	*mock.Call
}

// DeleteUnverifiedIdentities is a helper method to define mock.On call
//   - provider string
//   - sub string
func (_e *MockIdentityRepository_Expecter) DeleteUnverifiedIdentities(provider interface{}, sub interface{}) *MockIdentityRepository_DeleteUnverifiedIdentities_Call {
	return &MockIdentityRepository_DeleteUnverifiedIdentities_Call{Call: _e.mock.On("DeleteUnverifiedIdentities", provider, sub)}
}

func (_c *MockIdentityRepository_DeleteUnverifiedIdentities_Call) Run(run func(provider string, sub string)) *MockIdentityRepository_DeleteUnverifiedIdentities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentityRepository_DeleteUnverifiedIdentities_Call) Return(err error) *MockIdentityRepository_DeleteUnverifiedIdentities_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdentityRepository_DeleteUnverifiedIdentities_Call) RunAndReturn(run func(provider string, sub string) error) *MockIdentityRepository_DeleteUnverifiedIdentities_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdentityByProviderAndSub provides a mock function for the type MockIdentityRepository
func (_mock *MockIdentityRepository) FindIdentityByProviderAndSub(provider string, sub string) (*domain.UserIdentity, error) {
	ret := _mock.Called(provider, sub)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentityByProviderAndSub")
	}

	var r0 *domain.UserIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*domain.UserIdentity, error)); ok {
		return returnFunc(provider, sub)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *domain.UserIdentity); ok {
		r0 = returnFunc(provider, sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(provider, sub)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityRepository_FindIdentityByProviderAndSub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentityByProviderAndSub'
type MockIdentityRepository_FindIdentityByProviderAndSub_Call struct {
	*mock.Call
}

// FindIdentityByProviderAndSub is a helper method to define mock.On call
//   - provider string
//   - sub string
func (_e *MockIdentityRepository_Expecter) FindIdentityByProviderAndSub(provider interface{}, sub interface{}) *MockIdentityRepository_FindIdentityByProviderAndSub_Call {
	return &MockIdentityRepository_FindIdentityByProviderAndSub_Call{Call: _e.mock.On("FindIdentityByProviderAndSub", provider, sub)}
}

func (_c *MockIdentityRepository_FindIdentityByProviderAndSub_Call) Run(run func(provider string, sub string)) *MockIdentityRepository_FindIdentityByProviderAndSub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentityRepository_FindIdentityByProviderAndSub_Call) Return(userIdentity *domain.UserIdentity, err error) *MockIdentityRepository_FindIdentityByProviderAndSub_Call {
	_c.Call.Return(userIdentity, err)
	return _c
}

func (_c *MockIdentityRepository_FindIdentityByProviderAndSub_Call) RunAndReturn(run func(provider string, sub string) (*domain.UserIdentity, error)) *MockIdentityRepository_FindIdentityByProviderAndSub_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdentityByUserIDAndID provides a mock function for the type MockIdentityRepository
func (_mock *MockIdentityRepository) FindIdentityByUserIDAndID(userID uint, identityID uint) (*domain.UserIdentity, error) {
	ret := _mock.Called(userID, identityID)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentityByUserIDAndID")
	}

	var r0 *domain.UserIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*domain.UserIdentity, error)); ok {
		return returnFunc(userID, identityID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *domain.UserIdentity); ok {
		r0 = returnFunc(userID, identityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(userID, identityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityRepository_FindIdentityByUserIDAndID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentityByUserIDAndID'
type MockIdentityRepository_FindIdentityByUserIDAndID_Call struct {
	*mock.Call
}

// FindIdentityByUserIDAndID is a helper method to define mock.On call
//   - userID uint
//   - identityID uint
func (_e *MockIdentityRepository_Expecter) FindIdentityByUserIDAndID(userID interface{}, identityID interface{}) *MockIdentityRepository_FindIdentityByUserIDAndID_Call {
	return &MockIdentityRepository_FindIdentityByUserIDAndID_Call{Call: _e.mock.On("FindIdentityByUserIDAndID", userID, identityID)}
}

func (_c *MockIdentityRepository_FindIdentityByUserIDAndID_Call) Run(run func(userID uint, identityID uint)) *MockIdentityRepository_FindIdentityByUserIDAndID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIdentityRepository_FindIdentityByUserIDAndID_Call) Return(userIdentity *domain.UserIdentity, err error) *MockIdentityRepository_FindIdentityByUserIDAndID_Call {
	_c.Call.Return(userIdentity, err)
	return _c
}

func (_c *MockIdentityRepository_FindIdentityByUserIDAndID_Call) RunAndReturn(run func(userID uint, identityID uint) (*domain.UserIdentity, error)) *MockIdentityRepository_FindIdentityByUserIDAndID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type MockIdentityRepository
func (_mock *MockIdentityRepository) FindUserByEmail(email string) (*domain.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityRepository_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockIdentityRepository_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockIdentityRepository_Expecter) FindUserByEmail(email interface{}) *MockIdentityRepository_FindUserByEmail_Call {
	return &MockIdentityRepository_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", email)}
}

func (_c *MockIdentityRepository_FindUserByEmail_Call) Run(run func(email string)) *MockIdentityRepository_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIdentityRepository_FindUserByEmail_Call) Return(user *domain.User, err error) *MockIdentityRepository_FindUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIdentityRepository_FindUserByEmail_Call) RunAndReturn(run func(email string) (*domain.User, error)) *MockIdentityRepository_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// InsertIdentity provides a mock function for the type MockIdentityRepository
func (_mock *MockIdentityRepository) InsertIdentity(identity *domain.UserIdentity) error {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for InsertIdentity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.UserIdentity) error); ok {
		r0 = returnFunc(identity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdentityRepository_InsertIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertIdentity'
type MockIdentityRepository_InsertIdentity_Call struct {
	*mock.Call
}

// InsertIdentity is a helper method to define mock.On call
//   - identity *domain.UserIdentity
func (_e *MockIdentityRepository_Expecter) InsertIdentity(identity interface{}) *MockIdentityRepository_InsertIdentity_Call {
	return &MockIdentityRepository_InsertIdentity_Call{Call: _e.mock.On("InsertIdentity", identity)}
}

func (_c *MockIdentityRepository_InsertIdentity_Call) Run(run func(identity *domain.UserIdentity)) *MockIdentityRepository_InsertIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.UserIdentity
		if args[0] != nil {
			arg0 = args[0].(*domain.UserIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIdentityRepository_InsertIdentity_Call) Return(err error) *MockIdentityRepository_InsertIdentity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdentityRepository_InsertIdentity_Call) RunAndReturn(run func(identity *domain.UserIdentity) error) *MockIdentityRepository_InsertIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// InsertUser provides a mock function for the type MockIdentityRepository
func (_mock *MockIdentityRepository) InsertUser(user *domain.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdentityRepository_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type MockIdentityRepository_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockIdentityRepository_Expecter) InsertUser(user interface{}) *MockIdentityRepository_InsertUser_Call {
	return &MockIdentityRepository_InsertUser_Call{Call: _e.mock.On("InsertUser", user)}
}

func (_c *MockIdentityRepository_InsertUser_Call) Run(run func(user *domain.User)) *MockIdentityRepository_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIdentityRepository_InsertUser_Call) Return(err error) *MockIdentityRepository_InsertUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdentityRepository_InsertUser_Call) RunAndReturn(run func(user *domain.User) error) *MockIdentityRepository_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockIdentityRepository
func (_mock *MockIdentityRepository) WithTx(fn func(repo Repository) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(repo Repository) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdentityRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockIdentityRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - fn func(repo Repository) error
func (_e *MockIdentityRepository_Expecter) WithTx(fn interface{}) *MockIdentityRepository_WithTx_Call {
	return &MockIdentityRepository_WithTx_Call{Call: _e.mock.On("WithTx", fn)}
}

func (_c *MockIdentityRepository_WithTx_Call) Run(run func(fn func(repo Repository) error)) *MockIdentityRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(repo Repository) error
		if args[0] != nil {
			arg0 = args[0].(func(repo Repository) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIdentityRepository_WithTx_Call) Return(err error) *MockIdentityRepository_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdentityRepository_WithTx_Call) RunAndReturn(run func(fn func(repo Repository) error) error) *MockIdentityRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockRepository {
	mock := &MockRepository{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ActivateIdentity provides a mock function for the type MockRepository
func (_mock *MockRepository) ActivateIdentity(identityID uint) error {
	ret := _mock.Called(identityID)

	if len(ret) == 0 {
		panic("no return value specified for ActivateIdentity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(identityID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ActivateIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateIdentity'
type MockRepository_ActivateIdentity_Call struct {
	*mock.Call
}

// ActivateIdentity is a helper method to define mock.On call
//   - identityID uint
func (_e *MockRepository_Expecter) ActivateIdentity(identityID interface{}) *MockRepository_ActivateIdentity_Call {
	return &MockRepository_ActivateIdentity_Call{Call: _e.mock.On("ActivateIdentity", identityID)}
}

func (_c *MockRepository_ActivateIdentity_Call) Run(run func(identityID uint)) *MockRepository_ActivateIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ActivateIdentity_Call) Return(err error) *MockRepository_ActivateIdentity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ActivateIdentity_Call) RunAndReturn(run func(identityID uint) error) *MockRepository_ActivateIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTokenByStringAndUse provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteTokenByStringAndUse(tokenString string, tokenUse domain.TokenUse) error {
	ret := _mock.Called(tokenString, tokenUse)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTokenByStringAndUse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) error); ok {
		r0 = returnFunc(tokenString, tokenUse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteTokenByStringAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTokenByStringAndUse'
type MockRepository_DeleteTokenByStringAndUse_Call struct {
	*mock.Call
}

// DeleteTokenByStringAndUse is a helper method to define mock.On call
//   - tokenString string
//   - tokenUse domain.TokenUse
func (_e *MockRepository_Expecter) DeleteTokenByStringAndUse(tokenString interface{}, tokenUse interface{}) *MockRepository_DeleteTokenByStringAndUse_Call {
	return &MockRepository_DeleteTokenByStringAndUse_Call{Call: _e.mock.On("DeleteTokenByStringAndUse", tokenString, tokenUse)}
}

func (_c *MockRepository_DeleteTokenByStringAndUse_Call) Run(run func(tokenString string, tokenUse domain.TokenUse)) *MockRepository_DeleteTokenByStringAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteTokenByStringAndUse_Call) Return(err error) *MockRepository_DeleteTokenByStringAndUse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteTokenByStringAndUse_Call) RunAndReturn(run func(tokenString string, tokenUse domain.TokenUse) error) *MockRepository_DeleteTokenByStringAndUse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUnverifiedIdentities provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteUnverifiedIdentities(provider string, sub string) error {
	ret := _mock.Called(provider, sub)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUnverifiedIdentities")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(provider, sub)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteUnverifiedIdentities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUnverifiedIdentities'
type MockRepository_DeleteUnverifiedIdentities_Call struct {
	*mock.Call
}

// DeleteUnverifiedIdentities is a helper method to define mock.On call
//   - provider string
//   - sub string
func (_e *MockRepository_Expecter) DeleteUnverifiedIdentities(provider interface{}, sub interface{}) *MockRepository_DeleteUnverifiedIdentities_Call {
	return &MockRepository_DeleteUnverifiedIdentities_Call{Call: _e.mock.On("DeleteUnverifiedIdentities", provider, sub)}
}

func (_c *MockRepository_DeleteUnverifiedIdentities_Call) Run(run func(provider string, sub string)) *MockRepository_DeleteUnverifiedIdentities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteUnverifiedIdentities_Call) Return(err error) *MockRepository_DeleteUnverifiedIdentities_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteUnverifiedIdentities_Call) RunAndReturn(run func(provider string, sub string) error) *MockRepository_DeleteUnverifiedIdentities_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdentityByProviderAndSub provides a mock function for the type MockRepository
func (_mock *MockRepository) FindIdentityByProviderAndSub(provider string, sub string) (*domain.UserIdentity, error) {
	ret := _mock.Called(provider, sub)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentityByProviderAndSub")
	}

	var r0 *domain.UserIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*domain.UserIdentity, error)); ok {
		return returnFunc(provider, sub)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *domain.UserIdentity); ok {
		r0 = returnFunc(provider, sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(provider, sub)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindIdentityByProviderAndSub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentityByProviderAndSub'
type MockRepository_FindIdentityByProviderAndSub_Call struct {
	*mock.Call
}

// FindIdentityByProviderAndSub is a helper method to define mock.On call
//   - provider string
//   - sub string
func (_e *MockRepository_Expecter) FindIdentityByProviderAndSub(provider interface{}, sub interface{}) *MockRepository_FindIdentityByProviderAndSub_Call {
	return &MockRepository_FindIdentityByProviderAndSub_Call{Call: _e.mock.On("FindIdentityByProviderAndSub", provider, sub)}
}

func (_c *MockRepository_FindIdentityByProviderAndSub_Call) Run(run func(provider string, sub string)) *MockRepository_FindIdentityByProviderAndSub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindIdentityByProviderAndSub_Call) Return(userIdentity *domain.UserIdentity, err error) *MockRepository_FindIdentityByProviderAndSub_Call {
	_c.Call.Return(userIdentity, err)
	return _c
}

func (_c *MockRepository_FindIdentityByProviderAndSub_Call) RunAndReturn(run func(provider string, sub string) (*domain.UserIdentity, error)) *MockRepository_FindIdentityByProviderAndSub_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdentityByUserIDAndID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindIdentityByUserIDAndID(userID uint, identityID uint) (*domain.UserIdentity, error) {
	ret := _mock.Called(userID, identityID)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentityByUserIDAndID")
	}

	var r0 *domain.UserIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint, uint) (*domain.UserIdentity, error)); ok {
		return returnFunc(userID, identityID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint, uint) *domain.UserIdentity); ok {
		r0 = returnFunc(userID, identityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserIdentity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = returnFunc(userID, identityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindIdentityByUserIDAndID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentityByUserIDAndID'
type MockRepository_FindIdentityByUserIDAndID_Call struct {
	*mock.Call
}

// FindIdentityByUserIDAndID is a helper method to define mock.On call
//   - userID uint
//   - identityID uint
func (_e *MockRepository_Expecter) FindIdentityByUserIDAndID(userID interface{}, identityID interface{}) *MockRepository_FindIdentityByUserIDAndID_Call {
	return &MockRepository_FindIdentityByUserIDAndID_Call{Call: _e.mock.On("FindIdentityByUserIDAndID", userID, identityID)}
}

func (_c *MockRepository_FindIdentityByUserIDAndID_Call) Run(run func(userID uint, identityID uint)) *MockRepository_FindIdentityByUserIDAndID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindIdentityByUserIDAndID_Call) Return(userIdentity *domain.UserIdentity, err error) *MockRepository_FindIdentityByUserIDAndID_Call {
	_c.Call.Return(userIdentity, err)
	return _c
}

func (_c *MockRepository_FindIdentityByUserIDAndID_Call) RunAndReturn(run func(userID uint, identityID uint) (*domain.UserIdentity, error)) *MockRepository_FindIdentityByUserIDAndID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) FindUserByEmail(email string) (*domain.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockRepository_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockRepository_Expecter) FindUserByEmail(email interface{}) *MockRepository_FindUserByEmail_Call {
	return &MockRepository_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", email)}
}

func (_c *MockRepository_FindUserByEmail_Call) Run(run func(email string)) *MockRepository_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindUserByEmail_Call) Return(user *domain.User, err error) *MockRepository_FindUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_FindUserByEmail_Call) RunAndReturn(run func(email string) (*domain.User, error)) *MockRepository_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUsersByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) FindUsersByEmail(email string) ([]*domain.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindUsersByEmail")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*domain.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*domain.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindUsersByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUsersByEmail'
type MockRepository_FindUsersByEmail_Call struct {
	*mock.Call
}

// FindUsersByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockRepository_Expecter) FindUsersByEmail(email interface{}) *MockRepository_FindUsersByEmail_Call {
	return &MockRepository_FindUsersByEmail_Call{Call: _e.mock.On("FindUsersByEmail", email)}
}

func (_c *MockRepository_FindUsersByEmail_Call) Run(run func(email string)) *MockRepository_FindUsersByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindUsersByEmail_Call) Return(users []*domain.User, err error) *MockRepository_FindUsersByEmail_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_FindUsersByEmail_Call) RunAndReturn(run func(email string) ([]*domain.User, error)) *MockRepository_FindUsersByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUsersByID provides a mock function for the type MockRepository
func (_mock *MockRepository) FindUsersByID(context1 context.Context, uint32s []uint32) ([]*domain.User, error) {
	ret := _mock.Called(context1, uint32s)

	if len(ret) == 0 {
		panic("no return value specified for FindUsersByID")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint32) ([]*domain.User, error)); ok {
		return returnFunc(context1, uint32s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint32) []*domain.User); ok {
		r0 = returnFunc(context1, uint32s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint32) error); ok {
		r1 = returnFunc(context1, uint32s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindUsersByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUsersByID'
type MockRepository_FindUsersByID_Call struct {
	*mock.Call
}

// FindUsersByID is a helper method to define mock.On call
//   - context1 context.Context
//   - uint32s []uint32
func (_e *MockRepository_Expecter) FindUsersByID(context1 interface{}, uint32s interface{}) *MockRepository_FindUsersByID_Call {
	return &MockRepository_FindUsersByID_Call{Call: _e.mock.On("FindUsersByID", context1, uint32s)}
}

func (_c *MockRepository_FindUsersByID_Call) Run(run func(context1 context.Context, uint32s []uint32)) *MockRepository_FindUsersByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint32
		if args[1] != nil {
			arg1 = args[1].([]uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FindUsersByID_Call) Return(users []*domain.User, err error) *MockRepository_FindUsersByID_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_FindUsersByID_Call) RunAndReturn(run func(context1 context.Context, uint32s []uint32) ([]*domain.User, error)) *MockRepository_FindUsersByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetContacts provides a mock function for the type MockRepository
func (_mock *MockRepository) GetContacts(ctx context.Context, query string, excludeIds []uint32, currentUserID uint32) ([]*domain.User, error) {
	ret := _mock.Called(ctx, query, excludeIds, currentUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetContacts")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []uint32, uint32) ([]*domain.User, error)); ok {
		return returnFunc(ctx, query, excludeIds, currentUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []uint32, uint32) []*domain.User); ok {
		r0 = returnFunc(ctx, query, excludeIds, currentUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []uint32, uint32) error); ok {
		r1 = returnFunc(ctx, query, excludeIds, currentUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetContacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContacts'
type MockRepository_GetContacts_Call struct {
	*mock.Call
}

// GetContacts is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - excludeIds []uint32
//   - currentUserID uint32
func (_e *MockRepository_Expecter) GetContacts(ctx interface{}, query interface{}, excludeIds interface{}, currentUserID interface{}) *MockRepository_GetContacts_Call {
	return &MockRepository_GetContacts_Call{Call: _e.mock.On("GetContacts", ctx, query, excludeIds, currentUserID)}
}

func (_c *MockRepository_GetContacts_Call) Run(run func(ctx context.Context, query string, excludeIds []uint32, currentUserID uint32)) *MockRepository_GetContacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []uint32
		if args[2] != nil {
			arg2 = args[2].([]uint32)
		}
		var arg3 uint32
		if args[3] != nil {
			arg3 = args[3].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_GetContacts_Call) Return(users []*domain.User, err error) *MockRepository_GetContacts_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_GetContacts_Call) RunAndReturn(run func(ctx context.Context, query string, excludeIds []uint32, currentUserID uint32) ([]*domain.User, error)) *MockRepository_GetContacts_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenByStringAndUse provides a mock function for the type MockRepository
func (_mock *MockRepository) GetTokenByStringAndUse(tokenString string, tokenUse domain.TokenUse) (*domain.Token, error) {
	ret := _mock.Called(tokenString, tokenUse)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenByStringAndUse")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) (*domain.Token, error)); ok {
		return returnFunc(tokenString, tokenUse)
	}
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) *domain.Token); ok {
		r0 = returnFunc(tokenString, tokenUse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, domain.TokenUse) error); ok {
		r1 = returnFunc(tokenString, tokenUse)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetTokenByStringAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenByStringAndUse'
type MockRepository_GetTokenByStringAndUse_Call struct {
	*mock.Call
}

// GetTokenByStringAndUse is a helper method to define mock.On call
//   - tokenString string
//   - tokenUse domain.TokenUse
func (_e *MockRepository_Expecter) GetTokenByStringAndUse(tokenString interface{}, tokenUse interface{}) *MockRepository_GetTokenByStringAndUse_Call {
	return &MockRepository_GetTokenByStringAndUse_Call{Call: _e.mock.On("GetTokenByStringAndUse", tokenString, tokenUse)}
}

func (_c *MockRepository_GetTokenByStringAndUse_Call) Run(run func(tokenString string, tokenUse domain.TokenUse)) *MockRepository_GetTokenByStringAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetTokenByStringAndUse_Call) Return(token *domain.Token, err error) *MockRepository_GetTokenByStringAndUse_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockRepository_GetTokenByStringAndUse_Call) RunAndReturn(run func(tokenString string, tokenUse domain.TokenUse) (*domain.Token, error)) *MockRepository_GetTokenByStringAndUse_Call {
	_c.Call.Return(run)
	return _c
}

// InsertIdentity provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertIdentity(identity *domain.UserIdentity) error {
	ret := _mock.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for InsertIdentity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.UserIdentity) error); ok {
		r0 = returnFunc(identity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertIdentity'
type MockRepository_InsertIdentity_Call struct {
	*mock.Call
}

// InsertIdentity is a helper method to define mock.On call
//   - identity *domain.UserIdentity
func (_e *MockRepository_Expecter) InsertIdentity(identity interface{}) *MockRepository_InsertIdentity_Call {
	return &MockRepository_InsertIdentity_Call{Call: _e.mock.On("InsertIdentity", identity)}
}

func (_c *MockRepository_InsertIdentity_Call) Run(run func(identity *domain.UserIdentity)) *MockRepository_InsertIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.UserIdentity
		if args[0] != nil {
			arg0 = args[0].(*domain.UserIdentity)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_InsertIdentity_Call) Return(err error) *MockRepository_InsertIdentity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertIdentity_Call) RunAndReturn(run func(identity *domain.UserIdentity) error) *MockRepository_InsertIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// InsertToken provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertToken(token *domain.Token) error {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for InsertToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Token) error); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertToken'
type MockRepository_InsertToken_Call struct {
	*mock.Call
}

// InsertToken is a helper method to define mock.On call
//   - token *domain.Token
func (_e *MockRepository_Expecter) InsertToken(token interface{}) *MockRepository_InsertToken_Call {
	return &MockRepository_InsertToken_Call{Call: _e.mock.On("InsertToken", token)}
}

func (_c *MockRepository_InsertToken_Call) Run(run func(token *domain.Token)) *MockRepository_InsertToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Token
		if args[0] != nil {
			arg0 = args[0].(*domain.Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_InsertToken_Call) Return(err error) *MockRepository_InsertToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertToken_Call) RunAndReturn(run func(token *domain.Token) error) *MockRepository_InsertToken_Call {
	_c.Call.Return(run)
	return _c
}

// InsertUser provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertUser(user *domain.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type MockRepository_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockRepository_Expecter) InsertUser(user interface{}) *MockRepository_InsertUser_Call {
	return &MockRepository_InsertUser_Call{Call: _e.mock.On("InsertUser", user)}
}

func (_c *MockRepository_InsertUser_Call) Run(run func(user *domain.User)) *MockRepository_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_InsertUser_Call) Return(err error) *MockRepository_InsertUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertUser_Call) RunAndReturn(run func(user *domain.User) error) *MockRepository_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function for the type MockRepository
func (_mock *MockRepository) SearchUsers(ctx context.Context, query string, ids []uint32) ([]*domain.User, error) {
	ret := _mock.Called(ctx, query, ids)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []uint32) ([]*domain.User, error)); ok {
		return returnFunc(ctx, query, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []uint32) []*domain.User); ok {
		r0 = returnFunc(ctx, query, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []uint32) error); ok {
		r1 = returnFunc(ctx, query, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockRepository_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - ids []uint32
func (_e *MockRepository_Expecter) SearchUsers(ctx interface{}, query interface{}, ids interface{}) *MockRepository_SearchUsers_Call {
	return &MockRepository_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, query, ids)}
}

func (_c *MockRepository_SearchUsers_Call) Run(run func(ctx context.Context, query string, ids []uint32)) *MockRepository_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []uint32
		if args[2] != nil {
			arg2 = args[2].([]uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SearchUsers_Call) Return(users []*domain.User, err error) *MockRepository_SearchUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_SearchUsers_Call) RunAndReturn(run func(ctx context.Context, query string, ids []uint32) ([]*domain.User, error)) *MockRepository_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockRepository
func (_mock *MockRepository) WithTx(fn func(repo Repository) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(repo Repository) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - fn func(repo Repository) error
func (_e *MockRepository_Expecter) WithTx(fn interface{}) *MockRepository_WithTx_Call {
	return &MockRepository_WithTx_Call{Call: _e.mock.On("WithTx", fn)}
}

func (_c *MockRepository_WithTx_Call) Run(run func(fn func(repo Repository) error)) *MockRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(repo Repository) error
		if args[0] != nil {
			arg0 = args[0].(func(repo Repository) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_WithTx_Call) Return(err error) *MockRepository_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_WithTx_Call) RunAndReturn(run func(fn func(repo Repository) error) error) *MockRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockTokenService {
	mock := &MockTokenService{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// DeleteTokenByStringAndUse provides a mock function for the type MockTokenService
func (_mock *MockTokenService) DeleteTokenByStringAndUse(tokenString string, tokenUse domain.TokenUse) error {
	ret := _mock.Called(tokenString, tokenUse)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTokenByStringAndUse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) error); ok {
		r0 = returnFunc(tokenString, tokenUse)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_DeleteTokenByStringAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTokenByStringAndUse'
type MockTokenService_DeleteTokenByStringAndUse_Call struct {
	*mock.Call
}

// DeleteTokenByStringAndUse is a helper method to define mock.On call
//   - tokenString string
//   - tokenUse domain.TokenUse
func (_e *MockTokenService_Expecter) DeleteTokenByStringAndUse(tokenString interface{}, tokenUse interface{}) *MockTokenService_DeleteTokenByStringAndUse_Call {
	return &MockTokenService_DeleteTokenByStringAndUse_Call{Call: _e.mock.On("DeleteTokenByStringAndUse", tokenString, tokenUse)}
}

func (_c *MockTokenService_DeleteTokenByStringAndUse_Call) Run(run func(tokenString string, tokenUse domain.TokenUse)) *MockTokenService_DeleteTokenByStringAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_DeleteTokenByStringAndUse_Call) Return(err error) *MockTokenService_DeleteTokenByStringAndUse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_DeleteTokenByStringAndUse_Call) RunAndReturn(run func(tokenString string, tokenUse domain.TokenUse) error) *MockTokenService_DeleteTokenByStringAndUse_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenByStringAndUse provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GetTokenByStringAndUse(tokenString string, tokenUse domain.TokenUse) (*domain.Token, error) {
	ret := _mock.Called(tokenString, tokenUse)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenByStringAndUse")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) (*domain.Token, error)); ok {
		return returnFunc(tokenString, tokenUse)
	}
	if returnFunc, ok := ret.Get(0).(func(string, domain.TokenUse) *domain.Token); ok {
		r0 = returnFunc(tokenString, tokenUse)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, domain.TokenUse) error); ok {
		r1 = returnFunc(tokenString, tokenUse)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_GetTokenByStringAndUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenByStringAndUse'
type MockTokenService_GetTokenByStringAndUse_Call struct {
	*mock.Call
}

// GetTokenByStringAndUse is a helper method to define mock.On call
//   - tokenString string
//   - tokenUse domain.TokenUse
func (_e *MockTokenService_Expecter) GetTokenByStringAndUse(tokenString interface{}, tokenUse interface{}) *MockTokenService_GetTokenByStringAndUse_Call {
	return &MockTokenService_GetTokenByStringAndUse_Call{Call: _e.mock.On("GetTokenByStringAndUse", tokenString, tokenUse)}
}

func (_c *MockTokenService_GetTokenByStringAndUse_Call) Run(run func(tokenString string, tokenUse domain.TokenUse)) *MockTokenService_GetTokenByStringAndUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenService_GetTokenByStringAndUse_Call) Return(token *domain.Token, err error) *MockTokenService_GetTokenByStringAndUse_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenService_GetTokenByStringAndUse_Call) RunAndReturn(run func(tokenString string, tokenUse domain.TokenUse) (*domain.Token, error)) *MockTokenService_GetTokenByStringAndUse_Call {
	_c.Call.Return(run)
	return _c
}

// New provides a mock function for the type MockTokenService
func (_mock *MockTokenService) New(tokenType domain.TokenType, tokenUse domain.TokenUse, userID uint) (*domain.Token, error) {
	ret := _mock.Called(tokenType, tokenUse, userID)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 *domain.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.TokenType, domain.TokenUse, uint) (*domain.Token, error)); ok {
		return returnFunc(tokenType, tokenUse, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.TokenType, domain.TokenUse, uint) *domain.Token); ok {
		r0 = returnFunc(tokenType, tokenUse, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.TokenType, domain.TokenUse, uint) error); ok {
		r1 = returnFunc(tokenType, tokenUse, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockTokenService_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - tokenType domain.TokenType
//   - tokenUse domain.TokenUse
//   - userID uint
func (_e *MockTokenService_Expecter) New(tokenType interface{}, tokenUse interface{}, userID interface{}) *MockTokenService_New_Call {
	return &MockTokenService_New_Call{Call: _e.mock.On("New", tokenType, tokenUse, userID)}
}

func (_c *MockTokenService_New_Call) Run(run func(tokenType domain.TokenType, tokenUse domain.TokenUse, userID uint)) *MockTokenService_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.TokenType
		if args[0] != nil {
			arg0 = args[0].(domain.TokenType)
		}
		var arg1 domain.TokenUse
		if args[1] != nil {
			arg1 = args[1].(domain.TokenUse)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenService_New_Call) Return(token *domain.Token, err error) *MockTokenService_New_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenService_New_Call) RunAndReturn(run func(tokenType domain.TokenType, tokenUse domain.TokenUse, userID uint) (*domain.Token, error)) *MockTokenService_New_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccessToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) RefreshAccessToken(refreshTokenString string) (string, error) {
	ret := _mock.Called(refreshTokenString)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(refreshTokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(refreshTokenString)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(refreshTokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockTokenService_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - refreshTokenString string
func (_e *MockTokenService_Expecter) RefreshAccessToken(refreshTokenString interface{}) *MockTokenService_RefreshAccessToken_Call {
	return &MockTokenService_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", refreshTokenString)}
}

func (_c *MockTokenService_RefreshAccessToken_Call) Run(run func(refreshTokenString string)) *MockTokenService_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_RefreshAccessToken_Call) Return(s string, err error) *MockTokenService_RefreshAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_RefreshAccessToken_Call) RunAndReturn(run func(refreshTokenString string) (string, error)) *MockTokenService_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Save(token *domain.Token) error {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Token) error); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenService_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTokenService_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - token *domain.Token
func (_e *MockTokenService_Expecter) Save(token interface{}) *MockTokenService_Save_Call {
	return &MockTokenService_Save_Call{Call: _e.mock.On("Save", token)}
}

func (_c *MockTokenService_Save_Call) Run(run func(token *domain.Token)) *MockTokenService_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Token
		if args[0] != nil {
			arg0 = args[0].(*domain.Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_Save_Call) Return(err error) *MockTokenService_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenService_Save_Call) RunAndReturn(run func(token *domain.Token) error) *MockTokenService_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockUserService {
	mock := &MockUserService{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetContacts provides a mock function for the type MockUserService
func (_mock *MockUserService) GetContacts(ctx context.Context, query string, excludeIDs []uint32, currentUserID uint32) ([]*domain.User, error) {
	ret := _mock.Called(ctx, query, excludeIDs, currentUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetContacts")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []uint32, uint32) ([]*domain.User, error)); ok {
		return returnFunc(ctx, query, excludeIDs, currentUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []uint32, uint32) []*domain.User); ok {
		r0 = returnFunc(ctx, query, excludeIDs, currentUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []uint32, uint32) error); ok {
		r1 = returnFunc(ctx, query, excludeIDs, currentUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetContacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContacts'
type MockUserService_GetContacts_Call struct {
	*mock.Call
}

// GetContacts is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - excludeIDs []uint32
//   - currentUserID uint32
func (_e *MockUserService_Expecter) GetContacts(ctx interface{}, query interface{}, excludeIDs interface{}, currentUserID interface{}) *MockUserService_GetContacts_Call {
	return &MockUserService_GetContacts_Call{Call: _e.mock.On("GetContacts", ctx, query, excludeIDs, currentUserID)}
}

func (_c *MockUserService_GetContacts_Call) Run(run func(ctx context.Context, query string, excludeIDs []uint32, currentUserID uint32)) *MockUserService_GetContacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []uint32
		if args[2] != nil {
			arg2 = args[2].([]uint32)
		}
		var arg3 uint32
		if args[3] != nil {
			arg3 = args[3].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserService_GetContacts_Call) Return(users []*domain.User, err error) *MockUserService_GetContacts_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserService_GetContacts_Call) RunAndReturn(run func(ctx context.Context, query string, excludeIDs []uint32, currentUserID uint32) ([]*domain.User, error)) *MockUserService_GetContacts_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUsersByEmail(email string) ([]*domain.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByEmail")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*domain.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*domain.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUsersByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByEmail'
type MockUserService_GetUsersByEmail_Call struct {
	*mock.Call
}

// GetUsersByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserService_Expecter) GetUsersByEmail(email interface{}) *MockUserService_GetUsersByEmail_Call {
	return &MockUserService_GetUsersByEmail_Call{Call: _e.mock.On("GetUsersByEmail", email)}
}

func (_c *MockUserService_GetUsersByEmail_Call) Run(run func(email string)) *MockUserService_GetUsersByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_GetUsersByEmail_Call) Return(users []*domain.User, err error) *MockUserService_GetUsersByEmail_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserService_GetUsersByEmail_Call) RunAndReturn(run func(email string) ([]*domain.User, error)) *MockUserService_GetUsersByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByIDs provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUsersByIDs(ctx context.Context, userIDs []uint32) ([]*domain.User, error) {
	ret := _mock.Called(ctx, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByIDs")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint32) ([]*domain.User, error)); ok {
		return returnFunc(ctx, userIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uint32) []*domain.User); ok {
		r0 = returnFunc(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uint32) error); ok {
		r1 = returnFunc(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUsersByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByIDs'
type MockUserService_GetUsersByIDs_Call struct {
	*mock.Call
}

// GetUsersByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []uint32
func (_e *MockUserService_Expecter) GetUsersByIDs(ctx interface{}, userIDs interface{}) *MockUserService_GetUsersByIDs_Call {
	return &MockUserService_GetUsersByIDs_Call{Call: _e.mock.On("GetUsersByIDs", ctx, userIDs)}
}

func (_c *MockUserService_GetUsersByIDs_Call) Run(run func(ctx context.Context, userIDs []uint32)) *MockUserService_GetUsersByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uint32
		if args[1] != nil {
			arg1 = args[1].([]uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUsersByIDs_Call) Return(users []*domain.User, err error) *MockUserService_GetUsersByIDs_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserService_GetUsersByIDs_Call) RunAndReturn(run func(ctx context.Context, userIDs []uint32) ([]*domain.User, error)) *MockUserService_GetUsersByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function for the type MockUserService
func (_mock *MockUserService) SearchUsers(ctx context.Context, query string, userIDs []uint32) ([]*domain.User, error) {
	ret := _mock.Called(ctx, query, userIDs)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []*domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []uint32) ([]*domain.User, error)); ok {
		return returnFunc(ctx, query, userIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []uint32) []*domain.User); ok {
		r0 = returnFunc(ctx, query, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []uint32) error); ok {
		r1 = returnFunc(ctx, query, userIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockUserService_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - userIDs []uint32
func (_e *MockUserService_Expecter) SearchUsers(ctx interface{}, query interface{}, userIDs interface{}) *MockUserService_SearchUsers_Call {
	return &MockUserService_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, query, userIDs)}
}

func (_c *MockUserService_SearchUsers_Call) Run(run func(ctx context.Context, query string, userIDs []uint32)) *MockUserService_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []uint32
		if args[2] != nil {
			arg2 = args[2].([]uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_SearchUsers_Call) Return(users []*domain.User, err error) *MockUserService_SearchUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserService_SearchUsers_Call) RunAndReturn(run func(ctx context.Context, query string, userIDs []uint32) ([]*domain.User, error)) *MockUserService_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}
