######################
# dependencies layer #
######################
FROM golang:1.26.2-alpine AS deps

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download


#############
# dev layer #
#############
FROM deps AS dev
WORKDIR /app
RUN go install github.com/air-verse/air@latest
COPY . .
CMD ["air"]
