name: Chat CI

on:
    push:
        branches: [main]
        paths:
            - "services/chat/**"
    pull_request:
        branches: [main]
        paths:
            - "services/chat/**"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.26"

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v9
              with:
                  version: v2.12.1
                  working-directory: services/user
                  args: --timeout=5m

            - name: Run tests
              working-directory: services/chat
              env:
                  REFRESH_TOKEN_TTL: ${{ secrets.REFRESH_TOKEN_TTL }}
                  JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
                  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
                  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                  REFRESH_TOKEN_COOKIE_SECURE: ${{ secrets.REFRESH_TOKEN_COOKIE_SECURE }}
                  ACCESS_TOKEN_TTL: ${{ secrets.ACCESS_TOKEN_TTL }}
              run: go test ./...
